apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tripview-api-ingress
  namespace: team3ns
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripinsights-user-java
          servicePort: 80
        path: /api/user-java.*
      - backend:
          serviceName: tripinsights-poi
          servicePort: 80
        path: /api/poi.*
      - backend:
          serviceName: tripinsights-trips
          servicePort: 80
        path: /api/trips.*
      - backend:
          serviceName: tripinsights-userprofile
          servicePort: 80
        path: /api/user.*
