apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tripview-web-ingress
  namespace: webteam3ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripinsights-trip-viewer
          servicePort: 80
        path: /
      